# Generated by Django 5.1.2 on 2024-11-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description_1_subtitle',
            field=models.TextField(default='Wstaw tytuł pod pierwszy akapit'),
        ),
    ]
