# Generated by Django 5.1.2 on 2024-11-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_contactform_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='title',
            field=models.TextField(default='Kontakt'),
        ),
    ]
