# Generated by Django 5.1.2 on 2024-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_contactform_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description_1_subtitle', models.TextField(default='Wstaw tytuł pod pierwszy akapit')),
                ('description_1', models.TextField(default='Wstaw swój tekst.')),
                ('description_2_subtitle', models.TextField(blank=True, default='')),
                ('description_2', models.TextField(blank=True, default='')),
                ('description_3_subtitle', models.TextField(blank=True, default='')),
                ('description_3', models.TextField(blank=True, default='')),
                ('description_4_subtitle', models.TextField(blank=True, default='')),
                ('description_4', models.TextField(blank=True, default='')),
                ('description_5_subtitle', models.TextField(blank=True, default='')),
                ('description_5', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='title',
        ),
    ]
