# Generated by Django 5.1.2 on 2024-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_aboutuspage_remove_contactform_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='city',
            field=models.CharField(default='Wpisz miasto.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email_address',
            field=models.CharField(default='Wpisz email.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='house_number',
            field=models.CharField(default='Wpisz numer domu.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(default='Wpisz numer telefonu.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='street',
            field=models.CharField(default='Wpisz nazwę ulicy.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='vat_number',
            field=models.CharField(default='Wpisz numer identyfikacji podatkowej.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='working_days',
            field=models.CharField(default='Wpisz dni.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='working_hours',
            field=models.CharField(default='Wpisz godziny.', max_length=50),
        ),
    ]
